# OAuth2 관련
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 715398857869-8f3cgfmg9v4sp8rkfha8sa3prea0ac84.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          naver:
            clientId: ULEVlQReRHlE01ZnPO6v
            clientSecret: SyDHkdPpiC
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8099/login/oauth2/code/naver
            scope: nickname, email, phone

          kakao:
            client-id: 6b6d1c1c627e863062d8e0088e89d046
            client-secret: Cwh2XGjUJFj6D9RRX9JUBanj3Ra53IP4
            redirect-uri: http://localhost:8099/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image

    # Provider 설정
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id





